# Site settings
title: GormanGames
email: 8076bgorman@gmail.com
description: >
    Cool web games that I write.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://gormangames.com" # the base hostname & protocol for your site
twitter_username: thebgorm
github_username: Normangorman

# Build settings
markdown: kramdown
